-- DB trips

--  Notes:
--  “ent_id / ent_type” (Notification, Votings) are polymorphic references (can point to different tables);
--  meta data tables: genres, moods, privacy_status

create extension if not exists pgcrypto;

create table if not exists privacy_status (
  priv_st_id int primary key,
  status_name varchar
);

create table if not exists priv_users (
  u_id int generated by default as identity primary key,
  email varchar unique,
  hash_pw varchar,
  role varchar,
  date_created timestamp not null,
  last_login timestamp not null,
  privacy_st int not null references privacy_status(priv_st_id),
  is_silenced boolean
);

create table if not exists users (
  u_id int primary key references priv_users(u_id) on delete cascade,  -- internal/admin key (1–1 with priv_users)
  user_uid uuid not null unique default gen_random_uuid(),       -- public-facing user id

  username varchar not null unique,
  bio text,
  prof_pic_url varchar
);


create table if not exists followings (
  -- user u_id follows following_id (both are users)
  u_id int not null references users(u_id) on delete cascade,
  following_id int not null references users(u_id) on delete cascade,
  is_friend boolean, -- Note: maybe get rid of this feature
                    -- just use a query (if A follows B and B follows A)

  primary key (u_id, following_id),
  constraint chk_followings_no_self_follow check (u_id <> following_id)
);

create table if not exists notifications (
  noti_id int generated by default as identity primary key,
  -- “ou_id” = owner/receiver user
  ou_id int not null  references users(u_id) on delete cascade,
  -- “user_id” = actor user who triggered the notification
  user_id int references users(u_id) on delete cascade,

  -- polymorphic target entity
  ent_id int, -- note: "Polymorphic FK (depends on ent_type)"
  ent_type varchar, -- note: "e.g. discussion, reply, follow, review, rating, list, etc."

  is_viewed boolean,
  date_created timestamp not null
);

create table if not exists reactions (
  v_id int generated by default as identity primary key,

  -- polymorphic target entity
  ent_id int, -- note: "Polymorphic FK (depends on ent_type)"
  ent_type varchar, -- note: "What create table if not exists ent_id points to"

  u_id int not null references users(u_id) on delete cascade,
  score int -- note: "+1 / -1"
);

create table if not exists scenes (
  scene_id int generated by default as identity primary key,   -- internal/admin key
  scene_uid uuid not null unique default gen_random_uuid(), -- public key

  name varchar,
  description text,
  image_url varchar,
  date_created timestamp not null,
  date_updated timestamp not null,
  official boolean,
  owner_id int not null references users(u_id) on delete cascade,
  followers int
);

create table if not exists threads (
  t_id int generated by default as identity primary key,          -- internal/admin key
  t_uid uuid not null unique default gen_random_uuid(),     -- public key

  title varchar,
  text text,
  date_created timestamp not null,
  u_id int not null references users(u_id) on delete cascade,
  scene_id int not null references scenes(scene_id) on delete cascade,
  likes int,
  dislikes int
);

create table if not exists replies (
  rep_id int generated by default as identity primary key,        -- internal/admin key
  rep_uid uuid not null unique default gen_random_uuid(),   -- public key

  text text,
  level int,

  thread_id int not null references threads(t_id) on delete cascade,       -- set for top-level replies
  parent_rep_id int not null references replies(rep_id) on delete cascade,  -- set for nested replies

  u_id int not null references users(u_id) on delete cascade,
  date_created timestamp not null,
  likes int,
  dislikes int
);


create table if not exists moods (
  mood_id int generated by default as identity primary key,
  name varchar
);

create table if not exists genres (
  gen_id int generated by default as identity primary key,
  name varchar unique
);


create table if not exists artists (
  art_id int generated by default as identity primary key,
  art_uid uuid not null unique default gen_random_uuid(),

  name varchar,
  description text,
  img_url varchar,
  spotify_url varchar,
  apple_url varchar,
  insta_url varchar,
  home_town varchar,
  type varchar,
  scene_id int references scenes(scene_id) on delete set null
);

create table if not exists albums (
  alb_id int generated by default as identity primary key,
  alb_uid uuid not null unique default gen_random_uuid(),

  name varchar,
  cover_url varchar,
  description text,
  duration int,
  n_of_songs int,
  rel_date date,
  prim_lang varchar,
  scene_id int references scenes(scene_id) on delete set null
);

create table if not exists artists_x_albums (
  art_id int not null references artists(art_id) on delete cascade,
  alb_id int not null references albums(alb_id) on delete cascade,
  primary key (art_id, alb_id)
);


create table if not exists artists_x_genres (
  art_id int not null references artists(art_id) on delete cascade,
  gen_id int not null references genres(gen_id) on delete cascade,
  primary key (art_id, gen_id)
);

create table if not exists albums_x_genres (
  alb_id int not null references albums(alb_id) on delete cascade,
  gen_id int not null references genres(gen_id) on delete cascade,
  primary key (alb_id, gen_id)
);

create table if not exists user_moods (
  umd_id int generated by default as identity primary key,
  mood_id int not null references moods(mood_id) on delete cascade,
  u_id int not null references users(u_id) on delete cascade,
  alb_id int not null references albums(alb_id) on delete cascade,

  constraint uq_user_moods_user_album unique (u_id, alb_id, mood_id)
);

create table if not exists reviews (
  rv_id int generated by default as identity primary key,
  rv_uid uuid not null unique default gen_random_uuid(),

  text text,
  u_id int not null references users(u_id) on delete cascade,
  alb_id int not null references albums(alb_id) on delete cascade,
  date_created timestamp not null,
  date_updated timestamp not null,
  
  unique (u_id, alb_id)
);

create table if not exists ratings (
  rt_id int generated by default as identity primary key,
  score int,
  u_id int not null references users(u_id) on delete cascade,
  alb_id int not null references albums(alb_id) on delete cascade,

  unique (u_id, alb_id)
);


create table if not exists mixtapes (
  mix_id int generated by default as identity primary key,
  mix_uid uuid not null unique default gen_random_uuid(),

  name varchar,
  description text,
  is_official boolean,
  owner_id int not null references users(u_id) on delete cascade,
  priv_st_id int not null references privacy_status(priv_st_id) on delete set null
);

create table if not exists mixtapes_x_albums (
  mx_id int not null references mixtapes(mix_id) on delete cascade,
  alb_id int not null references albums(alb_id) on delete cascade,
  position int, -- user can rank their albums in their mixtapes

  primary key (mx_id, alb_id)
);