-- Auto-generated from user_seed.csv
BEGIN;

-- Insert into priv_users first
INSERT INTO priv_users (u_id, email, hash_pw, role, date_created,last_login, privacy_st, is_silenced) VALUES (1, 'ava.miller1@example.com', 'hashed_pw_01', 'music_enjoyer', '11/5/25 12:00', '2/1/26 12:00', 400, FALSE) ON CONFLICT (u_id) DO UPDATE SET email=EXCLUDED.email, hash_pw=EXCLUDED.hash_pw, role=EXCLUDED.role, last_login=EXCLUDED.last_login, privacy_st=EXCLUDED.privacy_st, is_silenced=EXCLUDED.is_silenced;
INSERT INTO priv_users (u_id, email, hash_pw, role, date_created,last_login, privacy_st, is_silenced) VALUES (2, 'noah.johnson2@example.com', 'hashed_pw_02', 'music_enjoyer', '11/6/25 12:00', '1/31/26 12:00', 200, FALSE) ON CONFLICT (u_id) DO UPDATE SET email=EXCLUDED.email, hash_pw=EXCLUDED.hash_pw, role=EXCLUDED.role, last_login=EXCLUDED.last_login, privacy_st=EXCLUDED.privacy_st, is_silenced=EXCLUDED.is_silenced;
INSERT INTO priv_users (u_id, email, hash_pw, role, date_created,last_login, privacy_st, is_silenced) VALUES (3, 'mia.davis3@example.com', 'hashed_pw_03', 'music_enjoyer', '11/7/25 12:00', '1/30/26 12:00', 200, FALSE) ON CONFLICT (u_id) DO UPDATE SET email=EXCLUDED.email, hash_pw=EXCLUDED.hash_pw, role=EXCLUDED.role, last_login=EXCLUDED.last_login, privacy_st=EXCLUDED.privacy_st, is_silenced=EXCLUDED.is_silenced;
INSERT INTO priv_users (u_id, email, hash_pw, role, date_created,last_login, privacy_st, is_silenced) VALUES (4, 'liam.brown4@example.com', 'hashed_pw_04', 'music_enjoyer', '11/8/25 12:00', '1/29/26 12:00', 200, FALSE) ON CONFLICT (u_id) DO UPDATE SET email=EXCLUDED.email, hash_pw=EXCLUDED.hash_pw, role=EXCLUDED.role, last_login=EXCLUDED.last_login, privacy_st=EXCLUDED.privacy_st, is_silenced=EXCLUDED.is_silenced;
INSERT INTO priv_users (u_id, email, hash_pw, role, date_created,last_login, privacy_st, is_silenced) VALUES (5, 'sofia.wilson5@example.com', 'hashed_pw_05', 'music_enjoyer', '11/9/25 12:00', '1/28/26 12:00', 400, FALSE) ON CONFLICT (u_id) DO UPDATE SET email=EXCLUDED.email, hash_pw=EXCLUDED.hash_pw, role=EXCLUDED.role, last_login=EXCLUDED.last_login, privacy_st=EXCLUDED.privacy_st, is_silenced=EXCLUDED.is_silenced;
INSERT INTO priv_users (u_id, email, hash_pw, role, date_created,last_login, privacy_st, is_silenced) VALUES (6, 'ethan.moore6@example.com', 'hashed_pw_06', 'music_enjoyer', '11/10/25 12:00', '1/27/26 12:00', 400, TRUE) ON CONFLICT (u_id) DO UPDATE SET email=EXCLUDED.email, hash_pw=EXCLUDED.hash_pw, role=EXCLUDED.role, last_login=EXCLUDED.last_login, privacy_st=EXCLUDED.privacy_st, is_silenced=EXCLUDED.is_silenced;
INSERT INTO priv_users (u_id, email, hash_pw, role, date_created,last_login, privacy_st, is_silenced) VALUES (7, 'chloe.taylor7@example.com', 'hashed_pw_07', 'music_enjoyer', '11/11/25 12:00', '1/26/26 12:00', 200, FALSE) ON CONFLICT (u_id) DO UPDATE SET email=EXCLUDED.email, hash_pw=EXCLUDED.hash_pw, role=EXCLUDED.role, last_login=EXCLUDED.last_login, privacy_st=EXCLUDED.privacy_st, is_silenced=EXCLUDED.is_silenced;
INSERT INTO priv_users (u_id, email, hash_pw, role, date_created,last_login, privacy_st, is_silenced) VALUES (8, 'oliver.anderson8@example.com', 'hashed_pw_08', 'music_enjoyer', '11/12/25 12:00', '1/25/26 12:00', 200, FALSE) ON CONFLICT (u_id) DO UPDATE SET email=EXCLUDED.email, hash_pw=EXCLUDED.hash_pw, role=EXCLUDED.role, last_login=EXCLUDED.last_login, privacy_st=EXCLUDED.privacy_st, is_silenced=EXCLUDED.is_silenced;
INSERT INTO priv_users (u_id, email, hash_pw, role, date_created,last_login, privacy_st, is_silenced) VALUES (9, 'isabella.thomas9@example.com', 'hashed_pw_09', 'music_enjoyer', '11/13/25 12:00', '1/24/26 12:00', 200, FALSE) ON CONFLICT (u_id) DO UPDATE SET email=EXCLUDED.email, hash_pw=EXCLUDED.hash_pw, role=EXCLUDED.role, last_login=EXCLUDED.last_login, privacy_st=EXCLUDED.privacy_st, is_silenced=EXCLUDED.is_silenced;
INSERT INTO priv_users (u_id, email, hash_pw, role, date_created,last_login, privacy_st, is_silenced) VALUES (10, 'james.jackson10@example.com', 'hashed_pw_10', 'music_enjoyer', '11/14/25 12:00', '1/23/26 12:00', 400, FALSE) ON CONFLICT (u_id) DO UPDATE SET email=EXCLUDED.email, hash_pw=EXCLUDED.hash_pw, role=EXCLUDED.role, last_login=EXCLUDED.last_login, privacy_st=EXCLUDED.privacy_st, is_silenced=EXCLUDED.is_silenced;
INSERT INTO priv_users (u_id, email, hash_pw, role, date_created,last_login, privacy_st, is_silenced) VALUES (11, 'admin.amind@example.com', 'hashed_pw_11', 'admin', '11/14/25 12:00', '1/23/26 12:00', 200, TRUE) ON CONFLICT (u_id) DO UPDATE SET email=EXCLUDED.email, hash_pw=EXCLUDED.hash_pw, role=EXCLUDED.role, last_login=EXCLUDED.last_login, privacy_st=EXCLUDED.privacy_st, is_silenced=EXCLUDED.is_silenced;

-- Insert into users using u_id looked up by email
-- (1-1 with priv_users)
INSERT INTO users (u_id, username, bio, prof_pic_url) VALUES (1, 'avamiller1', 'Fellow music enjoyer. I love to sleep and eat and do everrything with music.', NULL) ON CONFLICT (u_id) DO UPDATE SET username=EXCLUDED.username, bio=EXCLUDED.bio, prof_pic_url=EXCLUDED.prof_pic_url;
INSERT INTO users (u_id, username, bio, prof_pic_url) VALUES (2, 'noahjohnson2', 'Fellow music enjoyer. I love to sleep and eat and do everrything with music.', NULL) ON CONFLICT (u_id) DO UPDATE SET username=EXCLUDED.username, bio=EXCLUDED.bio, prof_pic_url=EXCLUDED.prof_pic_url;
INSERT INTO users (u_id, username, bio, prof_pic_url) VALUES (3, 'miadavis3', NULL, 'https://example.com/profiles/miadavis3.jpg') ON CONFLICT (u_id) DO UPDATE SET username=EXCLUDED.username, bio=EXCLUDED.bio, prof_pic_url=EXCLUDED.prof_pic_url;
INSERT INTO users (u_id, username, bio, prof_pic_url) VALUES (4, 'liambrown4', NULL, 'https://example.com/profiles/liambrown4.jpg') ON CONFLICT (u_id) DO UPDATE SET username=EXCLUDED.username, bio=EXCLUDED.bio, prof_pic_url=EXCLUDED.prof_pic_url;
INSERT INTO users (u_id, username, bio, prof_pic_url) VALUES (5, 'sofiawilson5', NULL, NULL) ON CONFLICT (u_id) DO UPDATE SET username=EXCLUDED.username, bio=EXCLUDED.bio, prof_pic_url=EXCLUDED.prof_pic_url;
INSERT INTO users (u_id, username, bio, prof_pic_url) VALUES (6, 'ethanmoore6', NULL, NULL) ON CONFLICT (u_id) DO UPDATE SET username=EXCLUDED.username, bio=EXCLUDED.bio, prof_pic_url=EXCLUDED.prof_pic_url;
INSERT INTO users (u_id, username, bio, prof_pic_url) VALUES (7, 'chloetaylor7', NULL, NULL) ON CONFLICT (u_id) DO UPDATE SET username=EXCLUDED.username, bio=EXCLUDED.bio, prof_pic_url=EXCLUDED.prof_pic_url;
INSERT INTO users (u_id, username, bio, prof_pic_url) VALUES (8, 'oliveranderson8', 'Fellow music enjoyer. I love to sleep and eat and do everrything with music.', 'https://example.com/profiles/oliveranderson8.jpg') ON CONFLICT (u_id) DO UPDATE SET username=EXCLUDED.username, bio=EXCLUDED.bio, prof_pic_url=EXCLUDED.prof_pic_url;
INSERT INTO users (u_id, username, bio, prof_pic_url) VALUES (9, 'isabellathomas9', 'Fellow music enjoyer. I love to sleep and eat and do everrything with music.', 'https://example.com/profiles/isabellathomas9.jpg') ON CONFLICT (u_id) DO UPDATE SET username=EXCLUDED.username, bio=EXCLUDED.bio, prof_pic_url=EXCLUDED.prof_pic_url;
INSERT INTO users (u_id, username, bio, prof_pic_url) VALUES (10, 'jamesjackson10', 'Fellow music enjoyer. I love to sleep and eat and do everrything with music.', 'https://example.com/profiles/jamesjackson10.jpg') ON CONFLICT (u_id) DO UPDATE SET username=EXCLUDED.username, bio=EXCLUDED.bio, prof_pic_url=EXCLUDED.prof_pic_url;
INSERT INTO users (u_id, username, bio, prof_pic_url) VALUES (11, 'the_first', 'Creator of website :)', 'https://i.pinimg.com/474x/d1/79/c5/d179c5c424ed339058effcb85c3f0f49.jpg') ON CONFLICT (u_id) DO UPDATE SET username=EXCLUDED.username, bio=EXCLUDED.bio, prof_pic_url=EXCLUDED.prof_pic_url;

COMMIT;
